services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports:
        - "1433:1433"
    volumes:
        - ./database:/var/opt/mssql/data
    
  diplomaproject.webapi:
    image: diplomaproject.webapi
    build:
      context: .
      dockerfile: DiplomaProject.WebApi/Dockerfile
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=database;Initial Catalog=DiplomaProjectDB;Persist Security Info=False;User ID=sa;Password=Martirosyan11;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;;
    depends_on:
      - database
    ports:
        - "80:80"
        - "443:443"
