global using System.Net;
global using System.Reflection;
global using System.Text.Json;
global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
// global using DiplomaProject.Application.DTOs;
global using DiplomaProject.Application.Interfaces;
// global using DiplomaProject.Application.Mappings;
// global using DiplomaProject.Application.UseCases.Orders.Commands;
// global using DiplomaProject.Application.UseCases.SimpleA.Commands;
// global using DiplomaProject.Application.UseCases.SimpleA.DomainEventHandlers.SimpleASomeFieldUpdated;
// global using DiplomaProject.Application.UseCases.SimpleA.Queries;
global using DiplomaProject.WebApi.AutofacModules;
// global using DiplomaProject.Domain.AggregatesModel.OrderAggregate;
// global using DiplomaProject.Domain.AggregatesModel.SimpleAAggregate;
global using DiplomaProject.Domain.Exceptions;
global using DiplomaProject.Domain.Services.External;
global using DiplomaProject.Infrastructure.Persistence.Behaviours;
global using DiplomaProject.Infrastructure.Persistence.DbContexts;
global using DiplomaProject.Infrastructure.Persistence.InitialDataSeeding;
global using DiplomaProject.Infrastructure.Persistence.Repositories;
global using DiplomaProject.Infrastructure.Shared.ExternalServices;
global using DiplomaProject.WebApi.Middlewares;
global using AppContext = DiplomaProject.Infrastructure.Persistence.DbContexts.AppContext;