global using System.Net;
global using System.Reflection;
global using System.Text.Json;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using DiplomaProject.Application.Interfaces;
global using DiplomaProject.Domain.Exceptions;
global using DiplomaProject.Domain.Services.External;
global using DiplomaProject.Infrastructure.Persistence.Behaviours;
global using DiplomaProject.Infrastructure.Persistence.DbContexts;
global using DiplomaProject.Infrastructure.Persistence.InitialDataSeeding;
global using DiplomaProject.Infrastructure.Persistence.Repositories;
global using DiplomaProject.Infrastructure.Shared.ExternalServices;
global using DiplomaProject.WebApi.Middlewares;
global using AppContext = DiplomaProject.Infrastructure.Persistence.DbContexts.AppContext;