global using Mapster;
global using MapsterMapper;
global using MediatR;
// global using sample.Application.DTOs;
// global using sample.Application.Extensions;
// global using sample.Domain.AggregatesModel.OrderAggregate;
// global using sample.Domain.AggregatesModel.SimpleAAggregate;
// global using sample.Domain.Events;
// global using sample.Domain.Events.Orders;
// global using sample.Domain.Exceptions;
// global using sample.Domain.Services.External;